// Lightweight "city, state" suggestion list for the wizard's address/location fields — no real
// geocoding service is wired up (client-side/mock-data-driven, consistent with the rest of the
// app), so this backs a simple substring-match autocomplete instead. Covers all 36 states + FCT
// with their capital plus a couple of other well-known cities/towns per state.
export const NIGERIA_LOCATIONS = [
  'Abuja, FCT',
  'Gwagwalada, FCT',
  'Kubwa, FCT',
  'Umuahia, Abia',
  'Aba, Abia',
  'Yola, Adamawa',
  'Mubi, Adamawa',
  'Uyo, Akwa Ibom',
  'Ikot Ekpene, Akwa Ibom',
  'Awka, Anambra',
  'Onitsha, Anambra',
  'Nnewi, Anambra',
  'Jos, Plateau',
  'Bukuru, Plateau',
  'Damaturu, Yobe',
  'Potiskum, Yobe',
  'Bauchi, Bauchi',
  'Azare, Bauchi',
  'Yenagoa, Bayelsa',
  'Makurdi, Benue',
  'Gboko, Benue',
  'Maiduguri, Borno',
  'Biu, Borno',
  'Calabar, Cross River',
  'Ikom, Cross River',
  'Asaba, Delta',
  'Warri, Delta',
  'Sapele, Delta',
  'Abakaliki, Ebonyi',
  'Afikpo, Ebonyi',
  'Benin City, Edo',
  'Auchi, Edo',
  'Ado Ekiti, Ekiti',
  'Enugu, Enugu',
  'Nsukka, Enugu',
  'Gombe, Gombe',
  'Kumo, Gombe',
  'Owerri, Imo',
  'Orlu, Imo',
  'Dutse, Jigawa',
  'Hadejia, Jigawa',
  'Kaduna, Kaduna',
  'Zaria, Kaduna',
  'Kano, Kano',
  'Katsina, Katsina',
  'Funtua, Katsina',
  'Birnin Kebbi, Kebbi',
  'Lokoja, Kogi',
  'Okene, Kogi',
  'Ilorin, Kwara',
  'Offa, Kwara',
  'Ikeja, Lagos',
  'Lagos Island, Lagos',
  'Surulere, Lagos',
  'Lekki, Lagos',
  'Ajah, Lagos',
  'Badagry, Lagos',
  'Lafia, Nasarawa',
  'Keffi, Nasarawa',
  'Minna, Niger',
  'Bida, Niger',
  'Abeokuta, Ogun',
  'Sagamu, Ogun',
  'Akure, Ondo',
  'Ondo Town, Ondo',
  'Osogbo, Osun',
  'Ile-Ife, Osun',
  'Ibadan, Oyo',
  'Ogbomoso, Oyo',
  'Port Harcourt, Rivers',
  'Bonny, Rivers',
  'Sokoto, Sokoto',
  'Gusau, Zamfara',
  'Jalingo, Taraba',
  'Wukari, Taraba',
];

export function searchLocations(query, limit = 6) {
  const term = (query || '').trim().toLowerCase();
  if (!term) return [];
  return NIGERIA_LOCATIONS.filter((loc) => loc.toLowerCase().includes(term)).slice(0, limit);
}
